### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by FaganAfandiyev**

### CODE REVIEW

**Review by pentestfunctions — CHANGES_REQUESTED** [review]
Be careful about submitting your known_devices.txt (You included your devices mac addresses)

**Review by FaganAfandiyev — COMMENTED** [review]
Fixing Douple Printing

**Comment by FaganAfandiyev** [comment]
> Be careful about submitting your known_devices.txt (You included your devices mac addresses)

lmao didnt see untill i pushed

**Comment by pentestfunctions** [comment]
Merged your changes.

**Pull request merged**
